### ISSUE TITLE
Linking apache text library.

### ISSUE THREAD

**Issue by GHRik** [GHRik/SjpAPI#2]
It is problem when i try to link SjpAPI.jar on other project.

REPRODUCED:

- Make project and link only SjpApi.jar , try to run 
```
String json = sjpApi.getWord("słowo");
```
RESULT:
```
2021-02-22 20:24:51.972 16857-16857/com.pomocnaliterka E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.pomocnaliterka, PID: 16857
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/commons/lang3/StringUtils;
        at com.sjp.sjpapi.CurlWrapper.deleteHeadFromOutput(CurlWrapper.java:14)
        at com.sjp.sjpapi.CurlHelper.getOutputFromCurl(CurlHelper.java:19)
        at com.sjp.sjpapi.SjpAPI.getWord(SjpAPI.java:15)
        at com.pomocnaliterka.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:31)
        at com.pomocnaliterka.-$$Lambda$MainActivity$VYDZTwWW-eBHh9aAkt_YK-rAlwc.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:7448)
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.commons.lang3.StringUtils" on path: DexPathList[[zip file "/data/app/~~C1zb4zGlLCSyaZCa7KUhFQ==/com.pomocnaliterka-H0zEfadWfPSiVA5gEn69mg==/base.apk"],nativeLibraryDirectories=[/data/app/~~C1zb4zGlLCSyaZCa7KUhFQ==/com.pomocnaliterka-H0zEfadWfPSiVA5gEn69mg==/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.sjp.sjpapi.CurlWrapper.deleteHeadFromOutput(CurlWrapper.java:14) 
        at com.sjp.sjpapi.CurlHelper.getOutputFromCurl(CurlHelper.java:19) 
        at com.sjp.sjpapi.SjpAPI.getWord(SjpAPI.java:15) 
        at com.pomocnaliterka.MainActivity.lambda$onCreate$0$MainActivity(MainActivity.java:31) 
        at com.pomocnaliterka.-$$Lambda$MainActivity$VYDZTwWW-eBHh9aAkt_YK-rAlwc.onClick(Unknown Source:6) 
        at android.view.View.performClick(View.java:7448) 
        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

Expected:
- Get word in json format.

WORKAROUND:
- Add **commons-lang3-3.11** as extended library to your project.

**Comment by GHRik** [comment]
Workaround:
https://github.com/GHRik/SjpAPI/commit/c05daad785177dade0459445d0467c404264a6d7

**Comment by GHRik** [comment]
This commit resolve issue:
https://github.com/GHRik/SjpAPI/commit/a7ce10c1e84083cb53113054b67c0eddee40efc8
